name = "dennis-muticia-portfolio"
main = "_worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./"

[env.production]
name = "dennis-muticia-portfolio"

[env.staging]
name = "dennis-muticia-portfolio-staging"

# Custom domain configuration
[[routes]]
pattern = "dennismuticia.dev/*"
zone_name = "dennismuticia.dev"

[[routes]]
pattern = "www.dennismuticia.dev/*"
zone_name = "dennismuticia.dev" 